apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nginx-gitops
  namespace: argocd

spec:
  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  source:
    repoURL: https://github.com/terrancey1700/devops-platform.git
    targetRevision: feature
    path: k8s/gitops-app

  destination:
    server: https://kubernetes.default.svc
    namespace: default
