name: Terraform CI

on:
  pull_request:
    branches: [main]
    paths:
      - "infra/**"

jobs:
  terraform:
    name: Terraform fmt validate plan
    runs-on: ubuntu-latest

    defaults:
      runs:
        working-directory: "infra/**"
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.7

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan